dirr_activities/activities/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from activities import views

urlpatterns = patterns('',
    url(r'^(?P<activity_id>\d+)/$', views.view_activity, name='view_activity'),
)

dirr_activities/dirr_activities/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'dirr_activities.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/', include('users.urls', namespace='users')),
    url(r'^', include('main.urls', namespace='main')),
    url(r'^activities/', include('activities.urls', namespace='activities')),
    url(r'^bookings/', include('bookings.urls', namespace='bookings')),
)

dirr_activities/main/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from main import views

urlpatterns = patterns('',
    url(r'^$', views.main, name='main'),
    )

dirr_activities/main/models.py
from django.db import models

# Create your models here.

dirr_activities/main/views.py
from django.shortcuts import render
from activities.models import Activity

# Create your views here.


def main(request):

    activities = Activity.objects.all()
    return render(request, 'main/main.html', {'activities': activities})

dirr_activities/templates/main/main.html
{% extends "base.html" %}

{% block title %}Main{% endblock %}

{% block content %}

<div class="container">
    <h3>Aktiviteter</h3>
    <dl>
    {% for activity in activities %}
        <a href="{% url 'activities:view_activity' activity.pk %}" class="list-group-item"> <dt>{{ activity.label }}</dt>
        <dd>{{activity.description}}</dd></a>
    {% endfor %}
    </dl>
</div>

{% endblock %}