dirr_activities/bookings/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from bookings import views

urlpatterns = patterns(
    '',
    url(r'^(?P<booking_id>\d+)/$', views.booking, name='booking'),
)

dirr_activities/dirr_activities/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'dirr_activities.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/', include('users.urls', namespace='users')),
    url(r'^', include('main.urls', namespace='main')),
    url(r'^activities/', include('activities.urls', namespace='activities')),
    url(r'^bookings/', include('bookings.urls', namespace='bookings')),
)

dirr_activities/main/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from main import views

urlpatterns = patterns('',
    url(r'^$', views.main, name='main'),
    )

dirr_activities/bookings/models.py
from django.db import models
from users.models import DirrUser
from activities.models import Activity, FeatureOption


class Booking(models.Model):

    def __unicode__(self):
        return unicode(self.activity)

    user = models.ForeignKey(DirrUser)
    activity = models.ForeignKey(Activity)
    amount = models.IntegerField(max_length=31)
    activity_date = models.DateTimeField()
    booking_date = models.DateTimeField(auto_now_add=True)
    modification_date = models.DateTimeField(auto_now=True)
    paid = models.DateTimeField(null=True)


class BookingOption(models.Model):

    def __unicode__(self):
        return unicode(self.feature_option)

    booking = models.ForeignKey('Booking')
    feature_option = models.ForeignKey(FeatureOption)


class People(models.Model):

    def __unicode__(self):
        return unicode(self.label)

    label = models.CharField(max_length=255)
    booking = models.ForeignKey('Booking')
    adult = models.IntegerField(null=True)
    youth = models.IntegerField(null=True)
    child = models.IntegerField(null=True)
    student = models.IntegerField(null=True)
    senior = models.IntegerField(null=True)

dirr_activities/bookings/forms.py
from django import forms
from bookings.models import Booking
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Fieldset, Field
from django.core.urlresolvers import reverse


class BookingForm(forms.ModelForm):

    helper = FormHelper()
    helper.form_action = 'bookings:booking'
    helper.form_method = 'POST'
    helper.add_input(Submit('edit_booking', 'Sign Up', css_class='btn btn-success'))

    class Meta:
        model = Booking
        exclude = ['user', 'activity', 'amount']

dirr_activities/bookings/views.py
from django.shortcuts import render
from bookings.models import Booking

def booking(request, booking_id):
    current_booking = Booking.objects.get(pk=booking_id);
    people = current_booking.people_set.all()
    p = people[0]
    total = p.senior + p.adult + p.youth + p.child + p.student
    return render(request, 'bookings/booking.html', {'current_booking': current_booking, 'p': p, 'total': total})

dirr_activities/templates/bookings/booking.html
{% extends "base.html" %}

{% block title %}{{ current_booking }}{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <h2 class="text-center"> {{ current_booking.activity }} </h2>
        <p class="text-center">{{ current_booking.activity.description }}</p>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">Alternativ</h3>
                </div>
                <div class="panel-body">
                    {% for option in current_booking.bookingoption_set.all %}
                    <h3>{{ option.feature_option.feature }}</h3>
                    <p>{{ option.feature_option }}</p>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">Deltagare</h3>
                </div>
                <div class="panel-body">
                    {% if p.adult != 0 %}
                    <h3>Vuxna: {{ p.adult }}</h3>
                    {% endif %}
                    {% if p.youth != 0 %}
                    <h3>Ungdomar: {{ p.youth }}</h3>
                    {% endif %}
                    {% if p.child != 0 %}
                    <h3>Barn: {{ p.child }}</h3>
                    {% endif %}
                    {% if p.student != 0 %}
                    <h3>Studenter: {{ p.student }}</h3>
                    {% endif %}
                    {% if p.senior != 0 %}
                    <h3>Pensionärer: {{ p.senior }}</h3>
                    {% endif %}
                    <h3>Totalt antal deltagare: {{ total }}</h3>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">Info</h3>
                </div>
                <div class="panel-body">
                    <h3>{{ current_booking.activity_date }}</h3>
                    <h3>Pris: {{ current_booking.amount }} kr</h3>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}