dirr_activities/dirr_activities/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'dirr_activities.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/', include('users.urls', namespace='users')),
    url(r'^', include('main.urls', namespace='main')),
    url(r'^activities/', include('activities.urls', namespace='activities')),
    url(r'^bookings/', include('bookings.urls', namespace='bookings')),
)

dirr_activities/main/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from main import views

urlpatterns = patterns('',
    url(r'^$', views.main, name='main'),
    )

dirr_activities/users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from users import views

urlpatterns = patterns('',
    url(r'^$', views.login_view, name='login'),
    url(r'^auth/$', views.authenticate_view, name='authenticate'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^sign_up/$', views.sign_up_view, name='sign_up'),
    )

dirr_activities/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.0/css/jasny-bootstrap.min.css">
    {% block head %}
    {% endblock %}
    {% include "bootstrap.html" %}
</head>
<body style="padding-top: 20px; padding-bottom: 20px;">
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand">Dirr Activities</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'main:main'%}">Main</a></li>
                </ul>
                <div class="nav navbar-right">
                    {% block extra_btn %}
                    {% endblock %}
                     {% if user.is_authenticated %}
                    <a class="btn btn-default navbar-btn" href="{% url 'users:logout' %}">Sign out</a>
                    {% else %}
                    <a class="btn btn-default navbar-btn" href="{% url 'users:login' %}">Sign in</a>
                    {% endif %}

                </div>
                <div class="nav navbar-right">
                    {% if user.is_authenticated %}
                    <a class="navbar-text">Signed in as: {{ user.get_full_name }}</a>
                    {% else %}
                    <a class="navbar-text" href="{% url 'users:sign_up' %}">Sign up</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</div>
{% block content %}
{% endblock %}
</body>
</html>

dirr_activities/templates/bootstrap.html
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">